// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yourttoo.Api.DataAccess;

#nullable disable

namespace Yourttoo.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251026114822_AddUserAvatar")]
    partial class AddUserAvatar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Yourttoo.DTOs.Models.AdditionalText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("published");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.ToTable("AdditionalText");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FAQSectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FAQSectionId");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.ToTable("FAQContent");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.ToTable("FAQSection");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DSTOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("GMTOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("IcaoCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("IataCode")
                        .IsUnique();

                    b.HasIndex("IcaoCode")
                        .IsUnique();

                    b.HasIndex("TimeZone");

                    b.HasIndex("ZoneId");

                    b.ToTable("Airports", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("CountryId");

                    b.HasIndex("RegionId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Continent");

                    b.HasIndex("Currency");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("TimeZone");

                    b.HasIndex("ZoneId");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PromotionArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PromotionAreaPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PromotionArea");

                    b.HasIndex("PromotionAreaPriority");

                    b.ToTable("Zones", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("Main category classification of the tag");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("URL to the icon image for the tag");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("URL to the main image for the tag");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("Unique identifier key for the tag");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active")
                        .HasComment("Current status of the tag");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("Sub-category classification of the tag");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("SearchKeyword")
                        .HasComment("Type of tag (Category, Feature, Theme, etc.)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Display value of the tag");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Tags_Category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Tags_CreatedAt");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_Tags_Key");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tags_Status");

                    b.HasIndex("SubCategory")
                        .HasDatabaseName("IX_Tags_SubCategory");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Tags_Type");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Tags_UpdatedAt");

                    b.HasIndex("Value")
                        .HasDatabaseName("IX_Tags_Value");

                    b.HasIndex("Category", "SubCategory")
                        .HasDatabaseName("IX_Tags_Category_SubCategory");

                    b.HasIndex("Type", "Status")
                        .HasDatabaseName("IX_Tags_Type_Status");

                    b.ToTable("Tags", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tags_Status", "Status IN ('Active', 'Inactive', 'Pending', 'Deleted', 'Archived', 'Draft', 'Approved', 'Rejected', 'Suspended', 'Expired', 'Completed', 'Cancelled', 'Processing', 'On_Hold', 'New', 'Updated', 'Verified', 'Unverified')");

                            t.HasCheckConstraint("CK_Tags_Type", "Type IN ('Category', 'Feature', 'Theme', 'Topic', 'Destination', 'Service', 'Audience', 'Style', 'PriceRange', 'SearchKeyword')");
                        });
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Users.Account", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Agency");

                    b.Property<string>("ApiKeys")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsTwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPasswordResetAt")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordChangedAt")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetTokenExpiresAt")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<string>("TwoFactorEnabledAt")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TwoFactorMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.HasIndex("AccountType")
                        .HasDatabaseName("IX_Accounts_AccountType");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_Email");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Accounts_Status");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AccessTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("es");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Europe/Madrid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Users_Status");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.AdditionalText", b =>
                {
                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Content", b1 =>
                        {
                            b1.Property<Guid>("AdditionalTextId")
                                .HasColumnType("TEXT");

                            b1.HasKey("AdditionalTextId");

                            b1.ToTable("AdditionalText");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalTextId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextAdditionalTextId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(2000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextAdditionalTextId", "Id");

                                    b2.ToTable("AdditionalText");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextAdditionalTextId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Title", b1 =>
                        {
                            b1.Property<Guid>("AdditionalTextId")
                                .HasColumnType("TEXT");

                            b1.HasKey("AdditionalTextId");

                            b1.ToTable("AdditionalText");

                            b1.ToJson("Title");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalTextId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextAdditionalTextId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextAdditionalTextId", "Id");

                                    b2.ToTable("AdditionalText");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextAdditionalTextId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Content");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQContent", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQSection", "FAQSection")
                        .WithMany("Contents")
                        .HasForeignKey("FAQSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Content", b1 =>
                        {
                            b1.Property<Guid>("FAQContentId")
                                .HasColumnType("TEXT");

                            b1.HasKey("FAQContentId");

                            b1.ToTable("FAQContent");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("FAQContentId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextFAQContentId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(2000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextFAQContentId", "Id");

                                    b2.ToTable("FAQContent");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextFAQContentId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Title", b1 =>
                        {
                            b1.Property<Guid>("FAQContentId")
                                .HasColumnType("TEXT");

                            b1.HasKey("FAQContentId");

                            b1.ToTable("FAQContent");

                            b1.ToJson("Title");

                            b1.WithOwner()
                                .HasForeignKey("FAQContentId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextFAQContentId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextFAQContentId", "Id");

                                    b2.ToTable("FAQContent");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextFAQContentId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("FAQSection");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQSection", b =>
                {
                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Title", b1 =>
                        {
                            b1.Property<Guid>("FAQSectionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("FAQSectionId");

                            b1.ToTable("FAQSection");

                            b1.ToJson("Title");

                            b1.WithOwner()
                                .HasForeignKey("FAQSectionId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextFAQSectionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextFAQSectionId", "Id");

                                    b2.ToTable("FAQSection");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextFAQSectionId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Airport", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("AirportId")
                                .HasColumnType("TEXT");

                            b1.HasKey("AirportId");

                            b1.ToTable("Airports");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("AirportId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextAirportId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextAirportId", "Id");

                                    b2.ToTable("Airports");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextAirportId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("AirportId")
                                .HasColumnType("TEXT");

                            b1.HasKey("AirportId");

                            b1.ToTable("Airports");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("AirportId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextAirportId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextAirportId", "Id");

                                    b2.ToTable("Airports");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextAirportId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.City", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("TEXT");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("CityId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextCityId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextCityId", "Id");

                                    b2.ToTable("Cities");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextCityId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("TEXT");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("CityId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextCityId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextCityId", "Id");

                                    b2.ToTable("Cities");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextCityId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Country");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Country", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Zone", "Zone")
                        .WithMany("Countries")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("CountryId")
                                .HasColumnType("TEXT");

                            b1.HasKey("CountryId");

                            b1.ToTable("Countries");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextCountryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextCountryId", "Id");

                                    b2.ToTable("Countries");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextCountryId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("CountryId")
                                .HasColumnType("TEXT");

                            b1.HasKey("CountryId");

                            b1.ToTable("Countries");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextCountryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextCountryId", "Id");

                                    b2.ToTable("Countries");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextCountryId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Region", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("RegionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("RegionId");

                            b1.ToTable("Regions");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextRegionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextRegionId", "Id");

                                    b2.ToTable("Regions");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextRegionId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("RegionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("RegionId");

                            b1.ToTable("Regions");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextRegionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextRegionId", "Id");

                                    b2.ToTable("Regions");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextRegionId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Country");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Zone", b =>
                {
                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("ZoneId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ZoneId");

                            b1.ToTable("Zones");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("ZoneId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextZoneId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextZoneId", "Id");

                                    b2.ToTable("Zones");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextZoneId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("ZoneId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ZoneId");

                            b1.ToTable("Zones");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("ZoneId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextZoneId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextZoneId", "Id");

                                    b2.ToTable("Zones");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextZoneId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.Tag", b =>
                {
                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TagId");

                            b1.ToTable("Tags");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("TagId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextTagId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextTagId", "Id");

                                    b2.ToTable("Tags");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextTagId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TagId");

                            b1.ToTable("Tags");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("TagId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextTagId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextTagId", "Id");

                                    b2.ToTable("Tags");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextTagId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQSection", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Zone", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
