// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yourttoo.Api.DataAccess;

#nullable disable

namespace Yourttoo.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251023112200_ZoneCountryRelationship2")]
    partial class ZoneCountryRelationship2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("TagCategoryTag", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TagCategoryTag");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.AdditionalText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("published");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.ToTable("AdditionalText");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Authentication.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Authentication.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Authentication.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FAQSectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FAQSectionId");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.ToTable("FAQContent");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.ToTable("FAQSection");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DSTOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("GMTOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("IATACode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ICAOCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("CountryId");

                    b.HasIndex("IATACode")
                        .IsUnique();

                    b.HasIndex("ICAOCode")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.HasIndex("TimeZone");

                    b.HasIndex("ZoneId");

                    b.ToTable("Airports", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("CountryId");

                    b.HasIndex("RegionId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Continent");

                    b.HasIndex("Currency");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("TimeZone");

                    b.HasIndex("ZoneId");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PromotionArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PromotionAreaPriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PromotionArea");

                    b.HasIndex("PromotionAreaPriority");

                    b.ToTable("Zones", (string)null);
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.TagCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Filtering")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TagCategory");
                });

            modelBuilder.Entity("TagCategoryTag", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Tagging.TagCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yourttoo.DTOs.Models.Tagging.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.AdditionalText", b =>
                {
                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Content", b1 =>
                        {
                            b1.Property<Guid>("AdditionalTextId")
                                .HasColumnType("TEXT");

                            b1.HasKey("AdditionalTextId");

                            b1.ToTable("AdditionalText");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalTextId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextAdditionalTextId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(2000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextAdditionalTextId", "Id");

                                    b2.ToTable("AdditionalText");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextAdditionalTextId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Title", b1 =>
                        {
                            b1.Property<Guid>("AdditionalTextId")
                                .HasColumnType("TEXT");

                            b1.HasKey("AdditionalTextId");

                            b1.ToTable("AdditionalText");

                            b1.ToJson("Title");

                            b1.WithOwner()
                                .HasForeignKey("AdditionalTextId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextAdditionalTextId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextAdditionalTextId", "Id");

                                    b2.ToTable("AdditionalText");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextAdditionalTextId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Content");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Authentication.UserRole", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Authentication.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yourttoo.DTOs.Models.Authentication.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQContent", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQSection", "FAQSection")
                        .WithMany("Contents")
                        .HasForeignKey("FAQSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Content", b1 =>
                        {
                            b1.Property<Guid>("FAQContentId")
                                .HasColumnType("TEXT");

                            b1.HasKey("FAQContentId");

                            b1.ToTable("FAQContent");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("FAQContentId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextFAQContentId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(2000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextFAQContentId", "Id");

                                    b2.ToTable("FAQContent");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextFAQContentId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Title", b1 =>
                        {
                            b1.Property<Guid>("FAQContentId")
                                .HasColumnType("TEXT");

                            b1.HasKey("FAQContentId");

                            b1.ToTable("FAQContent");

                            b1.ToJson("Title");

                            b1.WithOwner()
                                .HasForeignKey("FAQContentId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextFAQContentId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextFAQContentId", "Id");

                                    b2.ToTable("FAQContent");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextFAQContentId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("FAQSection");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQSection", b =>
                {
                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Title", b1 =>
                        {
                            b1.Property<Guid>("FAQSectionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("FAQSectionId");

                            b1.ToTable("FAQSection");

                            b1.ToJson("Title");

                            b1.WithOwner()
                                .HasForeignKey("FAQSectionId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextFAQSectionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextFAQSectionId", "Id");

                                    b2.ToTable("FAQSection");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextFAQSectionId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Airport", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("AirportId")
                                .HasColumnType("TEXT");

                            b1.HasKey("AirportId");

                            b1.ToTable("Airports");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("AirportId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextAirportId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextAirportId", "Id");

                                    b2.ToTable("Airports");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextAirportId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("AirportId")
                                .HasColumnType("TEXT");

                            b1.HasKey("AirportId");

                            b1.ToTable("Airports");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("AirportId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextAirportId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextAirportId", "Id");

                                    b2.ToTable("Airports");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextAirportId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.City", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("TEXT");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("CityId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextCityId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextCityId", "Id");

                                    b2.ToTable("Cities");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextCityId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("TEXT");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("CityId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextCityId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextCityId", "Id");

                                    b2.ToTable("Cities");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextCityId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Country");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Country", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Zone", "Zone")
                        .WithMany("Countries")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("CountryId")
                                .HasColumnType("TEXT");

                            b1.HasKey("CountryId");

                            b1.ToTable("Countries");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextCountryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextCountryId", "Id");

                                    b2.ToTable("Countries");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextCountryId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("CountryId")
                                .HasColumnType("TEXT");

                            b1.HasKey("CountryId");

                            b1.ToTable("Countries");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextCountryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextCountryId", "Id");

                                    b2.ToTable("Countries");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextCountryId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Region", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yourttoo.DTOs.Models.Geolocation.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("RegionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("RegionId");

                            b1.ToTable("Regions");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextRegionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextRegionId", "Id");

                                    b2.ToTable("Regions");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextRegionId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("RegionId")
                                .HasColumnType("TEXT");

                            b1.HasKey("RegionId");

                            b1.ToTable("Regions");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("RegionId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextRegionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextRegionId", "Id");

                                    b2.ToTable("Regions");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextRegionId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Country");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Zone", b =>
                {
                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("ZoneId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ZoneId");

                            b1.ToTable("Zones");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("ZoneId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextZoneId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextZoneId", "Id");

                                    b2.ToTable("Zones");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextZoneId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("ZoneId")
                                .HasColumnType("TEXT");

                            b1.HasKey("ZoneId");

                            b1.ToTable("Zones");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("ZoneId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextZoneId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextZoneId", "Id");

                                    b2.ToTable("Zones");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextZoneId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.Tag", b =>
                {
                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TagId");

                            b1.ToTable("Tags");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("TagId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextTagId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(2000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextTagId", "Id");

                                    b2.ToTable("Tags");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextTagId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Label", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TagId");

                            b1.ToTable("Tags");

                            b1.ToJson("Label");

                            b1.WithOwner()
                                .HasForeignKey("TagId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextTagId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextTagId", "Id");

                                    b2.ToTable("Tags");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextTagId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TagId");

                            b1.ToTable("Tags");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("TagId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextTagId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextTagId", "Id");

                                    b2.ToTable("Tags");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextTagId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Label")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.TagCategory", b =>
                {
                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Description", b1 =>
                        {
                            b1.Property<Guid>("TagCategoryId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TagCategoryId");

                            b1.ToTable("TagCategory");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("TagCategoryId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextTagCategoryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(2000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextTagCategoryId", "Id");

                                    b2.ToTable("TagCategory");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextTagCategoryId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.OwnsOne("Yourttoo.DTOs.Common.MultiLanguageText", "Name", b1 =>
                        {
                            b1.Property<Guid>("TagCategoryId")
                                .HasColumnType("TEXT");

                            b1.HasKey("TagCategoryId");

                            b1.ToTable("TagCategory");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("TagCategoryId");

                            b1.OwnsMany("Yourttoo.DTOs.Common.LanguageText", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("MultiLanguageTextTagCategoryId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Language")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Text")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("MultiLanguageTextTagCategoryId", "Id");

                                    b2.ToTable("TagCategory");

                                    b2.WithOwner()
                                        .HasForeignKey("MultiLanguageTextTagCategoryId");
                                });

                            b1.Navigation("Texts");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Authentication.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Authentication.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.FrequentlyAskedQuestions.FAQSection", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Geolocation.Zone", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
