// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yourttoo.Api.DataAccess;

#nullable disable

namespace Yourttoo.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251005163729_AdditionalTextTable")]
    partial class AdditionalTextTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("TagCategoryTag", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TagCategoryTag");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.TagCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Filtering")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TagCategory");
                });

            modelBuilder.Entity("TagCategoryTag", b =>
                {
                    b.HasOne("Yourttoo.DTOs.Models.Tagging.TagCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yourttoo.DTOs.Models.Tagging.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.Tag", b =>
                {
                    b.OwnsMany("Yourttoo.DTOs.Common.IdiomaticText", "Description", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT");

                            b1.HasKey("TagId", "Id");

                            b1.ToTable("Tags");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.OwnsMany("Yourttoo.DTOs.Common.IdiomaticText", "Label", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT");

                            b1.HasKey("TagId", "Id");

                            b1.ToTable("Tags");

                            b1.ToJson("Label");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.OwnsMany("Yourttoo.DTOs.Common.IdiomaticText", "Name", b1 =>
                        {
                            b1.Property<Guid>("TagId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT");

                            b1.HasKey("TagId", "Id");

                            b1.ToTable("Tags");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("TagId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Label");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Yourttoo.DTOs.Models.Tagging.TagCategory", b =>
                {
                    b.OwnsMany("Yourttoo.DTOs.Common.IdiomaticText", "Description", b1 =>
                        {
                            b1.Property<Guid>("TagCategoryId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TagCategoryId", "Id");

                            b1.ToTable("TagCategory");

                            b1.ToJson("Description");

                            b1.WithOwner()
                                .HasForeignKey("TagCategoryId");
                        });

                    b.OwnsMany("Yourttoo.DTOs.Common.IdiomaticText", "Name", b1 =>
                        {
                            b1.Property<Guid>("TagCategoryId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TagCategoryId", "Id");

                            b1.ToTable("TagCategory");

                            b1.ToJson("Name");

                            b1.WithOwner()
                                .HasForeignKey("TagCategoryId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
